### ISSUE TITLE
Some advices

### ISSUE THREAD

**Issue by HeartAndSoul001** [Krissh-C/T490-macOS#13]
about trackpad, maybe this can be work
<img width="1285" alt="截屏2023-04-18 08 46 06" src="https://user-images.githubusercontent.com/34875851/232640787-e38bc2f9-8f66-40da-b1f6-5d025052160d.png">
![Uploading 截屏2023-04-18 08.46.06.png…]()

**Comment by HeartAndSoul001** [comment]
pay attention to sequence of load

**Comment by ducks-c** [comment]
Bit late here but what seems to be the issue? The trackpad (and TrackPoint) work just fine.

**Comment by HeartAndSoul001** [comment]
> Bit late here but what seems to be the issue? The trackpad (and TrackPoint) work just fine.

hi, first, thank you for your EFI file, it is perfect for daily using. what I mean is the trackpad can be more smoothly after I change some kexts' loading(about VoodooRMI and VoodooInput)

**Comment by ducks-c** [comment]
Ah okay, I'll see if it changes anything. I'm going to release a new version of the EFI in a few days anyways, so I'll try this out and make the necessary changes with that.
