### ISSUE TITLE
t490 sleep/wake

### ISSUE THREAD

**Issue by jack338c** [Krissh-C/T490-macOS#8]
hello
I just apply your efi to my t490.it works smooth and fast! thank you
My t490 with your T490-macOS will sleep after the lip closed.but maybe after 1 hour.it will wake automatically.I test many times ,sitll no luck

Could you tell me how to solve this ?

thanks again for your awesome repository  
![Screenshot 2023-01-08 at 5 58 30 PM](https://user-images.githubusercontent.com/10782586/211190031-a88d09b3-8e47-433b-b915-07828841391c.png)

**Comment by ducks-c** [comment]
If the computer goes to sleep (fading led), and it wakes up after a while, this could be an issue with macOS waking up to check for updates, notifications, etc.

First step would be to run the below commands one at a time in terminal
```
sudo pmset autopoweroff 0
sudo pmset powernap 0
sudo pmset standby 0
sudo pmset proximitywake 0
sudo pmset tcpkeepalive 0
```
More info on these commands [here](https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#preparations)

Then also turn off Power Nap, Wake for Network Access and Hard Disk sleep. Do the same as the screenshot in System Settings > Battery > Options (Optimising video streaming on battery is optional, I recommend it though)
![image](https://user-images.githubusercontent.com/117280851/211190111-635111ac-7004-4578-a37c-75c77f001868.png)

Let me know if this fixes it for you :)

**Comment by jack338c** [comment]
did it and will check the sleep soon
but I found my one have no "put hard disks to sleep when possiable" option, why?

![Screenshot 2023-01-08 at 6 37 22 PM](https://user-images.githubusercontent.com/10782586/211191589-2b997a19-0f92-4a55-8cd5-7eca2579aa3c.png)
![Screenshot 2023-01-08 at 6 38 35 PM](https://user-images.githubusercontent.com/10782586/211191585-4ae86c0f-24c9-41c3-a630-399390ce4278.png)

**Comment by ducks-c** [comment]
That could only be for my installation as I'm running macOS off an external drive. If you want, try plugging in an external drive (not USB) and see if that option shows up.

**Comment by jack338c** [comment]
> 

ok,got it
thanks for your help and wish you a happy life 🥂

**Comment by jack338c** [comment]
> If the computer goes to sleep (fading led), and it wakes up after a while, this could be an issue with macOS waking up to check for updates, notifications, etc.
> 
> First step would be to run the below commands one at a time in terminal
> 
> ```
> sudo pmset autopoweroff 0
> sudo pmset powernap 0
> sudo pmset standby 0
> sudo pmset proximitywake 0
> sudo pmset tcpkeepalive 0
> ```
> 
> More info on these commands [here](https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#preparations)
> 
> Then also turn off Power Nap, Wake for Network Access and Hard Disk sleep. Do the same as the screenshot in System Settings > Battery > Options (Optimising video streaming on battery is optional, I recommend it though) ![image](https://user-images.githubusercontent.com/117280851/211190111-635111ac-7004-4578-a37c-75c77f001868.png)
> 
> Let me know if this fixes it for you :)

The issue is fixed .sleep now is perfect .thank you

Then I found a new issue on my t490.if I use hot conners to put display to sleep.my t490 will sleep automatically in several mintutes. otherwise it will not sleep automatically.

I want it will not sleep automatically when I put display to sleep.this is useful to me .when I leave pc .I would turn display off but pc is on

![Screenshot 2023-01-09 at 9 59 40 AM](https://user-images.githubusercontent.com/10782586/211232298-b2abef1e-91a6-454d-b40c-3bf62ba91e5f.png)

**Comment by ducks-c** [comment]
I'd suggest looking into apps such as [Amphetamine](https://apps.apple.com/us/app/amphetamine/id937984704) 
Don't really know what to do here 😅

**Comment by jack338c** [comment]
> I'd suggest looking into apps such as [Amphetamine](https://apps.apple.com/us/app/amphetamine/id937984704) Don't really know what to do here 😅

Yeah,this app is good for second display to me.
actually,I have a t450s which is also running macos.the hot conner have no conflict with sleep [https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore](https://github.com/CLAY-BIOS/Lenovo-ThinkPad-T450s-Hackintosh-Big-Sur-OpenCore)
Currently It's good enough for mine t490 👍 
thanks for your time 
![Screenshot 2023-01-10 at 10 01 09 AM](https://user-images.githubusercontent.com/10782586/211445007-fc2d7507-f40e-46ea-b8ca-db34435e4a29.png)

**Comment by jack338c** [comment]
I found the solution: runing something in terminal. then it will not sleep automatically
now iit's perfect to me
