### ISSUE TITLE
full screen on Youtube

### ISSUE THREAD

**Issue by jack338c** [Krissh-C/T490-macOS#9]
Hello
I found every time when it play Youtube videos on full screen .the display will fast flash sometime,like fast sway from side to side
no big deal ,but not sure is it only my t490 issue?
thanks and Hava good day !

**Comment by ducks-c** [comment]
Hey. Sorry for the late reply, got caught up with school stuff 😅
Could you provide a screen recording if possible? It'll help clarify what the problem is exactly.

**Comment by jack338c** [comment]
it's ok,thanks for your attention
now the issue is disapear after it rebooted
I will put link here for video later after the issue come back again 🥂
